Repository nasa/prog_models, pull requests merged in 2021-08, with the labels that each got.

#91 CodeFactor
  examples/future_loading.py
  examples/sim_valve.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/pneumatic_valve.py
  src/prog_models/prognostics_model.py
  src/prog_models/visualize.py
  tests/__init__.py
  tests/test_base_models.py
  tests/test_battery.py
Labels: bug

#92 More CodeFactor
  src/prog_models/exceptions.py
  src/prog_models/models/pneumatic_valve.py
  tests/test_pneumatic_valve.py
Labels: bug

#93 Added badges to readme
  README.md
Labels: documentation

#96 Save time as array in sim
  src/prog_models/prognostics_model.py
Labels: enhancement

#97 Add test of compatibility with prog_algs
  .github/workflows/python-package.yml
Labels: CI/CD

#98 New feature: set initial state in simulation
  src/prog_models/prognostics_model.py
  tests/test_base_models.py
Labels: enhancement

#99 Updates to Derived Param Feature
  examples/__init__.py
  examples/derived_params.py
  prog_model_template.py
  sphinx_config/getting_started.rst
  src/prog_models/models/battery_electrochem.py
  src/prog_models/prognostics_model.py
  tests/test_base_models.py
  tests/test_examples.py
  tutorial.ipynb
Labels: documentation, enhancement

#100 Implement Prediction Result
  src/prog_models/prognostics_model.py
  src/prog_models/sim_result.py
  tests/__main__.py
  tests/test_sim_result.py
  tutorial.ipynb
Labels: enhancement

#104 Expand tests to include individual models
  tests/test_battery.py
  tests/test_centrifugal_pump.py
  tests/test_pneumatic_valve.py
Labels: CI/CD

#105 Remove exec()
  tests/__main__.py
  tests/test_base_models.py
  tests/test_battery.py
  tests/test_centrifugal_pump.py
  tests/test_examples.py
  tests/test_pneumatic_valve.py
  tests/test_sim_result.py
Labels: CI/CD

#106 Resolve doc comments
  sphinx_config/dev_guide.rst
  sphinx_config/getting_started.rst
  sphinx_config/models.rst
  sphinx_config/prognostics_model.rst
Labels: documentation

#102 Fix Various Issues identified by partner
  examples/sim_pump.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/centrifugal_pump.py
  src/prog_models/models/pneumatic_valve.py
Labels: bug

#108 Added detailed updates to docs
  sphinx_config/getting_started.rst
Labels: documentation

#110 Removed unnecessary assignment
  src/prog_models/prognostics_model.py
Labels: bug

#111 Optional State Bounds
  prog_model_template.py
  src/prog_models/models/battery_circuit.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/centrifugal_pump.py
  src/prog_models/models/pneumatic_valve.py
  src/prog_models/prognostics_model.py
  tests/test_base_models.py
Labels: enhancement

#114 Fixed 2 LGTM alerts
  src/prog_models/models/pneumatic_valve.py
  src/prog_models/sim_result.py
Labels: bug

#122 State Bounds Example
  examples/__init__.py
  examples/new_model.py
  examples/state_limits.py
  tests/test_base_models.py
  tests/test_examples.py
Labels: enhancement

#124 Update getting_started.rst
  sphinx_config/getting_started.rst
Labels: documentation

#120 Make pole pairs and phases configurable
  src/prog_models/models/centrifugal_pump.py
Labels: enhancement

#126 A few minor Battery Model Optimizations
  src/prog_models/models/battery_electrochem.py
Labels: enhancement

#125 Fix States
  src/prog_models/models/battery_circuit.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/centrifugal_pump.py
Labels: documentation, enhancement
