Repository nasa/prog_models, pull requests merged in 2021-06, with the labels that each got.

#45 Fix bug in SOC Calculation
  examples/__init__.py
  examples/sim_battery_eol.py
  sphinx_config/getting_started.rst
  src/prog_models/models/battery_electrochem.py
  tests/test_examples.py
Labels: bug

#51 Pump Improvements
  .gitignore
  examples/sim_pump.py
  src/prog_models/models/__init__.py
  src/prog_models/models/centrifugal_pump.py
Labels: enhancement

#33 Added python3.9 compatibility
  .github/workflows/python-package.yml
  setup.py
  src/prog_models/__init__.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/prognostics_model.py
Labels: enhancement, good first issue

#52 Parameter Estimation
  examples/__init__.py
  examples/future_loading.py
  examples/model_gen.py
  examples/new_model.py
  examples/noise.py
  examples/param_est.py
  sphinx_config/getting_started.rst
  src/prog_models/models/battery_electrochem.py
  src/prog_models/prognostics_model.py
  tests/test_examples.py
  tutorial.ipynb
Labels: enhancement

#58 Parameters binding to default_parameters
  src/prog_models/prognostics_model.py
Labels: bug

#64 Dev Guide and Readme improvements
  README.md
  sphinx_config/dev_guide.rst
Labels: documentation
