Repository nasa/prog_models, pull requests merged in 2022-05, with the labels that each got.

#274 Implement monotonicity for SimResult
  src/prog_models/sim_result.py
  tests/test_sim_result.py
Labels: enhancement

#281 Bugfixes and suggested changes
  src/prog_models/prognostics_model.py
Labels: bug, component: surrogate

#224 Feature/surrogate model dmd
  examples/generate_surrogate.py
  src/prog_models/prognostics_model.py
Labels: enhancement, component: surrogate

#284 Adding ThrownObject drag testing
  tests/test_base_models.py
Labels: CI/CD

#285 Fixed MSE
  src/prog_models/prognostics_model.py
Labels: bug

#286 BatteryElectrochem missing kwargs
  src/prog_models/models/battery_electrochem.py
Labels: bug

#290 Moving skipped automatic example tests to manual testing
  tests/test_manual.py
Labels: CI/CD

#288 Surrogate Model Tests
  examples/generate_surrogate.py
  sphinx_config/getting_started.rst
  src/prog_models/prognostics_model.py
  tests/__main__.py
  tests/test_sim_result.py
  tests/test_surrogates.py
Labels: CI/CD, component: surrogate

#293 Codefactor resolutions
  src/prog_models/models/dcmotor.py
  src/prog_models/prognostics_model.py
  src/prog_models/utils/containers.py
Labels: bug

#294 Fix bug
  src/prog_models/prognostics_model.py
Labels: bug

#295 Creating script to automatically check files for copyright tag
  .github/workflows/python-package.yml
  scripts/test_copyright.py
  tests/__main__.py
  tests/test_battery.py
  tests/test_centrifugal_pump.py
  tests/test_pneumatic_valve.py
  tests/test_powertrain.py
Labels: enhancement, CI/CD

#299 Fix undefined dist
  src/prog_models/utils/parameters.py
Labels: bug

#297 Release Review Fixes
  examples/linear_model.py
  examples/model_gen.py
  examples/new_model.py
  examples/sim.py
  examples/sim_battery_eol.py
  examples/sim_powertrain.py
  examples/sim_pump.py
  examples/sim_valve.py
  examples/state_limits.py
  examples/vectorized.py
  src/prog_models/datasets/nasa_battery.py
  src/prog_models/datasets/nasa_cmapss.py
  src/prog_models/models/esc.py
  src/prog_models/sim_result.py
  tutorial.ipynb
Labels: documentation, CI/CD

#304 fix tuple issue
  src/prog_models/prognostics_model.py
Labels: bug

#305 Remove unnecessary deepcopies
  src/prog_models/prognostics_model.py
  src/prog_models/sim_result.py
Labels: bug

#303 Fixed issue with containers
  src/prog_models/utils/containers.py
Labels: bug

#309 hotfix v1.3.1
  src/prog_models/prognostics_model.py
  src/prog_models/sim_result.py
  src/prog_models/utils/containers.py
Labels: bug
