Repository nasa/prog_models, pull requests merged in 2022-01, with the labels that each got.

#179 Implement Linear Model
  examples/__init__.py
  examples/linear_model.py
  src/prog_models/__init__.py
  src/prog_models/linear_model.py
Labels: enhancement

#183 Add warning when setting param that will be overwritten
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/centrifugal_pump.py
  src/prog_models/models/pneumatic_valve.py
  tests/test_battery.py
  tests/test_centrifugal_pump.py
  tests/test_pneumatic_valve.py
Labels: bug, enhancement

#189 Typo correction in tutorial.ipynb
  .gitignore
  tutorial.ipynb
Labels: bug, documentation
