Repository nasa/prog_models, pull requests merged in 2022-04, with the labels that each got.

#253 Update load calculation at midpoint
  src/prog_models/prognostics_model.py
  tests/test_centrifugal_pump.py
Labels: enhancement

#248 Add CMAPSS Dataset
  src/prog_models/datasets/nasa_cmapss.py
Labels: enhancement

#264 Improved type hints
  src/prog_models/datasets/nasa_battery.py
  src/prog_models/datasets/nasa_cmapss.py
  src/prog_models/linear_model.py
  src/prog_models/models/battery_circuit.py
  src/prog_models/models/battery_electrochem.py
  src/prog_models/models/centrifugal_pump.py
  src/prog_models/models/pneumatic_valve.py
  src/prog_models/models/thrown_object.py
  src/prog_models/prognostics_model.py
  src/prog_models/sim_result.py
  src/prog_models/utils/containers.py
  src/prog_models/utils/noise_functions.py
  src/prog_models/utils/parameters.py
  src/prog_models/utils/progress_bar.py
  src/prog_models/visualize.py
Labels: documentation, enhancement

#132 DC Motor, ESC, and Powertrain Models
  examples/sim_powertrain.py
  sphinx_config/getting_started.rst
  sphinx_config/models.rst
  src/prog_models/models/__init__.py
  src/prog_models/models/dcmotor.py
  src/prog_models/models/esc.py
  src/prog_models/models/powertrain.py
  src/prog_models/utils/containers.py
  tests/__main__.py
  tests/test_examples.py
  tests/test_powertrain.py
Labels: enhancement

#265 Automatic legends for plotting function calls
  src/prog_models/sim_result.py
Labels: enhancement

#266 Custom error messages for downloading + testing datasets + manual testing file
  .github/workflows/python-package.yml
  sphinx_config/dev_guide.rst
  src/prog_models/datasets/nasa_battery.py
  src/prog_models/datasets/nasa_cmapss.py
  tests/__init__.py
  tests/__main__.py
  tests/test_datasets.py
  tests/test_manual.py
Labels: enhancement

#270 fix plot
  src/prog_models/visualize.py
Labels: bug
