Repository nasa/prog_models, pull requests merged in 2022-03, with the labels that each got.

#228 Matrix Model Approach 2: Container
  examples/matrix_model.py
  src/prog_models/prognostics_model.py
  src/prog_models/utils/containers.py
  tests/__init__.py
  tests/__main__.py
  tests/test_base_models.py
  tests/test_dict_like_matrix_wrapper.py
  tests/test_examples.py
Labels: enhancement

#237 Fixed behavior for vectorized models
  src/prog_models/prognostics_model.py
  src/prog_models/utils/containers.py
  tests/test_examples.py
Labels: bug

#239 Propagate Matrix work to linear model
  examples/linear_model.py
  src/prog_models/linear_model.py
  tests/test_base_models.py
Labels: enhancement

#227 Autotesting for Jupyter notebook tutorial files
  .github/workflows/python-package.yml
  tests/__init__.py
  tests/__main__.py
  tests/test_tutorials.py
Labels: enhancement, CI/CD

#247 Added delete functionality to container
  src/prog_models/utils/containers.py
  tests/test_dict_like_matrix_wrapper.py
Labels: enhancement

#252 Container and Process Noise Bugs
  src/prog_models/prognostics_model.py
  src/prog_models/utils/containers.py
Labels: bug

#245 Clear cache
  src/prog_models/datasets/nasa_battery.py
Labels: enhancement
